spring.application.name=trabalho

spring.datasource.url=jdbc:postgresql://localhost:5432/cliente_bd
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true